<a href="https://colab.research.google.com/github/rashisimpi/AIML-Cohort-8/blob/data-preprocessing/DATAcollection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving 8f35d745-2ed9-4ca4-b7ea-f355e6fd00c5_Data.csv to 8f35d745-2ed9-4ca4-b7ea-f355e6fd00c5_Data.csv

In [ ]:
import pandas as pd

# Replace with the exact uploaded file name
df = pd.read_csv("8f35d745-2ed9-4ca4-b7ea-f355e6fd00c5_Data.csv")

In [ ]:
df.head(5)

,Country Name,Country Code,Series Name,Series Code,2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],...,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
0,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,138.706821676113,178.954088379235,198.871115728727,221.763653873013,254.184249149336,274.218553561575,...,522.082215583898,525.469770891619,491.337221382603,496.6025042585,510.787063366811,356.496214115892,357.261152798144,413.757894705303,..,..
1,Afghanistan,AFG,Individuals using the Internet (% of population),IT.NET.USER.ZS,0.00472257,0.0045614,0.0878913,0.105809,1.22415,2.10712,...,11,13.5,16.8,17.6,17.0485,16.5143,17.1917,17.7089,..,..
2,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,625.82781544115,630.512327648462,815.432296267735,989.015463629244,1126.2973233912,1235.26660811771,...,1334.47050032928,1528.10422421284,1552.07372194919,1507.08559963484,1351.59166910879,1562.41617477738,1679.32762166466,1571.44918918981,1615.39635562849,..
3,Africa Eastern and Southern,AFE,Individuals using the Internet (% of population),IT.NET.USER.ZS,..,..,..,..,1.8,1.9,...,16.3,17.3,19.6,21.6,23.5,25,26.8,27.8,28.8,30.4
4,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,532.972787221754,619.337335030759,697.481256337088,838.213391665852,999.770023047319,1234.64185574403,...,1630.03943895258,1574.23056437855,1720.14009242722,2216.38505520833,2030.86165860293,2112.79407637079,2138.47315259913,1841.85506354867,1411.33702938476,..

In [ ]:
df.shape

(537, 29)

In [ ]:
df.columns

Index(['Country Name', 'Country Code', 'Series Name', 'Series Code',
       '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]', '2004 [YR2004]',
       '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]', '2008 [YR2008]',
       '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]', '2012 [YR2012]',
       '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]',
       '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]', '2020 [YR2020]',
       '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]', '2024 [YR2024]',
       '2025 [YR2025]'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 29 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   534 non-null    object
 1   Country Code   532 non-null    object
 2   Series Name    532 non-null    object
 3   Series Code    532 non-null    object
 4   2001 [YR2001]  532 non-null    object
 5   2002 [YR2002]  532 non-null    object
 6   2003 [YR2003]  532 non-null    object
 7   2004 [YR2004]  532 non-null    object
 8   2005 [YR2005]  532 non-null    object
 9   2006 [YR2006]  532 non-null    object
 10  2007 [YR2007]  532 non-null    object
 11  2008 [YR2008]  532 non-null    object
 12  2009 [YR2009]  532 non-null    object
 13  2010 [YR2010]  532 non-null    object
 14  2011 [YR2011]  532 non-null    object
 15  2012 [YR2012]  532 non-null    object
 16  2013 [YR2013]  532 non-null    object
 17  2014 [YR2014]  532 non-null    object
 18  2015 [YR2015]  532 non-null    object
 19  2016 [YR2016]  532 non-null    object
 20  2017 [YR2017]  532 non-null    object
 21  2018 [YR2018]  532 non-null    object
 22  2019 [YR2019]  532 non-null    object
 23  2020 [YR2020]  532 non-null    object
 24  2021 [YR2021]  532 non-null    object
 25  2022 [YR2022]  532 non-null    object
 26  2023 [YR2023]  532 non-null    object
 27  2024 [YR2024]  532 non-null    object
 28  2025 [YR2025]  532 non-null    object
dtypes: object(29)
memory usage: 121.8+ KB

In [ ]:
df.describe()

,Country Name,Country Code,Series Name,Series Code,2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],...,2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
count,534,532,532,532,532,532,532,532,532,532,...,532,532,532,532,532,532,532,532,532,532
unique,268,266,2,2,451,457,451,454,478,481,...,484,489,457,470,471,465,464,458,318,33
top,Zimbabwe,ZWE,GDP per capita (current US$),NY.GDP.PCAP.CD,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
freq,2,2,266,266,80,73,80,77,42,42,...,37,35,64,54,55,60,60,67,210,498

In [ ]:
df.isnull().sum()

Country Name     3
Country Code     5
Series Name      5
Series Code      5
2001 [YR2001]    5
2002 [YR2002]    5
2003 [YR2003]    5
2004 [YR2004]    5
2005 [YR2005]    5
2006 [YR2006]    5
2007 [YR2007]    5
2008 [YR2008]    5
2009 [YR2009]    5
2010 [YR2010]    5
2011 [YR2011]    5
2012 [YR2012]    5
2013 [YR2013]    5
2014 [YR2014]    5
2015 [YR2015]    5
2016 [YR2016]    5
2017 [YR2017]    5
2018 [YR2018]    5
2019 [YR2019]    5
2020 [YR2020]    5
2021 [YR2021]    5
2022 [YR2022]    5
2023 [YR2023]    5
2024 [YR2024]    5
2025 [YR2025]    5
dtype: int64